sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install tox-travis python-coveralls

# command to run tests
script:
  - tox

after_success:
  - coveralls
