# Travis setup.
# Tox + numpy + scipy + coveralls
#
# Notes:
# [1] Miniconda is used to quickly install numpy and scipy. Otherwise
#     their building time is too much for Travis.
#     See this gist for details: https://gist.github.com/dan-blanchard/7045057
#     See also http://conda.pydata.org/docs/travis.html

sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"

# For contents of install, see [1]
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export "PATH=$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - pip install --upgrade pip
  - conda create --quiet --name testenv python=$TRAVIS_PYTHON_VERSION numpy scipy  # See [1]
  - source activate testenv
  - pip install python-coveralls nose-cov flake8  # Not available via conda for OS X
  - python setup.py install

# Commands to run tests.
# Command nosetests is installed by nose-cov
script:
  - nosetests --with-cov --cov gazelib --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc
